version: "3"

services:
  master:
    image: locustio/locust
    network_mode: "host"
    ports:
      - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/tasks-odoo-website.py --master -H http://localhost:8089

  worker:
    image: locustio/locust
    network_mode: "host"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/tasks-odoo-website.py --worker --master-host localhost
